//! `sidebar-adapter-battery` — Battery adapter via starship-battery (Story 3.3).
//!
//! Provides battery percent, state, and power-rate readings via the
//! `starship-battery` crate. Emits `BatteryPercent`, `BatteryState`, and
//! `BatteryPowerRate` per physical battery.
//!
//! ## Architecture
//!
//! The real `starship_battery::Manager` is a concrete type whose `batteries()`
//! method returns an iterator yielding `Result<Battery>`. To make the adapter
//! unit-testable per the TDD contract (Story 3.3 calls for "mock battery 78%
//! charging → 3 readings" tests), we abstract behind a `BatteryBackend` trait.
//! Production code wires the real manager via `RealBatteryBackend`; tests
//! inject `MockBatteryBackend` (auto-generated by `mockall`).
//!
//! The adapter holds a `Mutex<B>` (mirroring Story 3.1's sysinfo adapter) so
//! `read_all` can take `&self` and still refresh. `SensorProvider::read_all`
//! is `&self` (Story 2.1), so interior mutability is required.
//!
//! ## Cited
//!
//! - Story 3.3 TDD contract (Happy Path #1, Boundary #1-#3)
//! - architecture.md §5.1 (Reading/MetricKind/Unit/BatteryState spec), §7.2
//! - nfr-thresholds.md T-1 (Lightweight < 0.1% CPU), T-20 (finite values only)
//! - guardrails.md G15 (Mutex poison recovery)

use std::sync::Mutex;

use sidebar_domain::reading::{finite, MetricKind, Reading, SensorId, Unit};
use sidebar_sensor::descriptor::{CostClass, ProviderTier, SensorDescriptor};
use sidebar_sensor::provider::SensorProvider;

pub mod backend;

use crate::backend::{BatteryBackend, BatterySnapshot, BatterySnapshotState};

/// Metrics emitted by this adapter — declared once so the descriptor is
/// `const`-constructible.
const BATTERY_METRICS: &[MetricKind] = &[
    MetricKind::BatteryPercent,
    MetricKind::BatteryState,
    MetricKind::BatteryPowerRate,
];

/// Descriptor for the battery adapter — `Tier::Basic`, `CostClass::Lightweight`.
///
/// Cited: Story 3.3 Technical Context. Not in the G11 HITL list.
const DESCRIPTOR: SensorDescriptor = SensorDescriptor::new(
    "battery",
    CostClass::Lightweight,
    BATTERY_METRICS,
    ProviderTier::Basic,
);

/// Battery-backed adapter. Holds a `Mutex` around the backend because
/// `refresh_and_snapshot` requires `&mut` and `SensorProvider::read_all` is
/// `&self`.
///
/// Generic over `B: BatteryBackend` so tests can substitute a mock. The
/// production convenience alias [`BatteryAdapter`] fixes `B =
/// RealBatteryBackend`.
pub struct BatteryAdapterGeneric<B: BatteryBackend> {
    backend: Mutex<B>,
}

/// Production adapter wired to the real `starship_battery::Manager`.
///
/// Equivalent to `BatteryAdapterGeneric<RealBatteryBackend>` but with a `new()`
/// constructor that initializes the real backend.
pub type BatteryAdapter = BatteryAdapterGeneric<backend::RealBatteryBackend>;

impl<B: BatteryBackend> BatteryAdapterGeneric<B> {
    /// Construct an adapter wrapping the given backend. The backend is wrapped
    /// in a `Mutex` so `read_all` (which is `&self` per the trait) can still
    /// call `&mut self` refresh methods.
    #[must_use]
    pub fn with_backend(backend: B) -> Self {
        Self {
            backend: Mutex::new(backend),
        }
    }
}

impl BatteryAdapter {
    /// Construct the production adapter backed by a real
    /// `starship_battery::Manager`.
    ///
    /// The first `read_all` call enumerates batteries; there is no eager
    /// refresh here (keeps cold-start cheap, NFR-3).
    #[must_use]
    pub fn new() -> Self {
        Self::with_backend(backend::RealBatteryBackend::new())
    }
}

impl Default for BatteryAdapter {
    fn default() -> Self {
        Self::new()
    }
}

impl<B: BatteryBackend + Send> SensorProvider for BatteryAdapterGeneric<B> {
    fn descriptor(&self) -> &SensorDescriptor {
        &DESCRIPTOR
    }

    fn read_all(&self) -> Vec<Reading> {
        // Lock once per tick. The lock is held for the duration of refresh +
        // snapshot extraction (microseconds on any modern machine). The poller
        // is single-threaded per adapter in v1, so contention is not a concern;
        // the Mutex exists only to satisfy the `&self` signature.
        //
        // G15: recover from poison rather than propagating the panic — the
        // poller's catch_unwind handles the FIRST panic, but the Mutex is left
        // poisoned; this `unwrap_or_else(|e| e.into_inner())` lets subsequent
        // ticks recover rather than tearing down the adapter permanently.
        let mut guard = self
            .backend
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        let snapshots = guard.refresh_and_snapshot();
        readings_from_snapshot(&snapshots)
    }
}

/// Translate a slice of [`BatterySnapshot`]s into the canonical `Vec<Reading>`.
///
/// Pulled out of `read_all` so unit tests can exercise the translation without
/// standing up a backend — this is where the TDD contract's "78% charging → 3
/// readings" assertions live.
///
/// # Finite-value policy (T-20)
///
/// Any reading whose `value` is `NaN` or `±Inf` is OMITTED (not emitted with a
/// sentinel). This matters for `energy_rate_watts` on drivers that return NaN
/// when the battery is idle (some Windows ACPI drivers do this); we drop those
/// readings rather than propagate NaN to the formatter.
///
/// # Sign convention (Boundary #3)
///
/// `energy_rate_watts` is passed through verbatim. `starship-battery` reports
/// positive on most platforms when discharging (battery draining) and negative
/// when charging on AC. The adapter does NOT normalize the sign — the GUI
/// formats it with the sign visible, which is the diagnostic value.
fn readings_from_snapshot(snapshots: &[BatterySnapshot]) -> Vec<Reading> {
    // One battery → up to 3 readings (percent, state, power-rate). The state
    // reading is ALWAYS finite (it's an ordinal 0..=3); percent and rate can
    // be NaN on some drivers, so they go through the T-20 finite filter.
    let mut out = Vec::with_capacity(snapshots.len() * 3);
    for s in snapshots {
        let inst = s.index.to_string();

        // --- BatteryPercent (0..=100, Unit::Percent) ---
        if let Some(pct) = finite(s.percent) {
            out.push(Reading::new(
                SensorId::new("battery", inst.clone()),
                MetricKind::BatteryPercent,
                pct,
                Unit::Percent,
            ));
        }

        // --- BatteryState (ordinal f64, Unit::Count) ---
        // The value is the BatteryState ordinal (Charging=0.0, Discharging=1.0,
        // Idle=2.0, Unknown=3.0) per sidebar_domain::BatteryState::to_value.
        // It is ALWAYS finite (an ordinal 0..=3), so no finite-filter needed.
        // The unit carries no physical dimension (it's a wire-format code); we
        // use Unit::Count as the canonical "unitless counter" per §5.1.
        let state_value = snapshot_state_to_domain(s.state).to_value();
        out.push(Reading::new(
            SensorId::new("battery", inst.clone()),
            MetricKind::BatteryState,
            state_value,
            Unit::Count,
        ));

        // --- BatteryPowerRate (Watts, sign = discharging direction) ---
        // Per Boundary #3: pass through verbatim. Positive = discharging on
        // most platforms, negative = charging on AC. The adapter MUST NOT
        // normalize the sign; NaN is filtered per T-20.
        if let Some(rate) = finite(s.energy_rate_watts) {
            out.push(Reading::new(
                SensorId::new("battery", inst),
                MetricKind::BatteryPowerRate,
                rate,
                Unit::Watts,
            ));
        }
    }
    out
}

/// Map the backend's plain-data state to the domain `BatteryState` ordinal.
///
/// `BatteryState::to_value()` (sidebar-domain) returns the stable f64 wire
/// format (Charging=0.0, Discharging=1.0, Idle=2.0, Unknown=3.0). The
/// `BatteryState` Reading's `value` carries that ordinal.
fn snapshot_state_to_domain(s: BatterySnapshotState) -> sidebar_domain::reading::BatteryState {
    match s {
        BatterySnapshotState::Charging => sidebar_domain::reading::BatteryState::Charging,
        BatterySnapshotState::Discharging => sidebar_domain::reading::BatteryState::Discharging,
        BatterySnapshotState::Idle => sidebar_domain::reading::BatteryState::Idle,
        BatterySnapshotState::Unknown => sidebar_domain::reading::BatteryState::Unknown,
    }
}

#[cfg(test)]
mod tests {
    //! Story 3.3 TDD contract tests.
    //!
    //! These tests exercise `readings_from_snapshot` + the adapter via a mock
    //! backend. The real `starship_battery::Manager` is exercised by the
    //! `real_backend_returns_some_readings` smoke test below (only meaningful
    //! on machines with a battery — the dev machine has one at 96% charging).
    //!
    //! Cited:
    //!   - Story 3.3 TDD contract (Happy Path #1, Boundary #1-#3)
    //!   - architecture.md §5.1 (Reading/MetricKind/Unit/BatteryState spec)
    //!   - nfr-thresholds.md T-1 (Lightweight), T-20 (finite only)
    //!   - guardrails.md G15 (Mutex poison recovery)

    use super::*;
    use mockall::mock;
    use sidebar_domain::format::format_battery;
    use sidebar_domain::reading::{BatteryState, MetricKind, Unit};
    use sidebar_sensor::provider::SensorProvider;
    use std::sync::Arc;

    // Auto-mock the `BatteryBackend` trait so tests can inject canned
    // snapshots without standing up a real `starship_battery::Manager`.
    mock! {
        pub FakeBackend {}
        impl BatteryBackend for FakeBackend {
            fn refresh_and_snapshot(&mut self) -> Vec<BatterySnapshot>;
        }
    }

    // ----- Happy Path #1: 78% charging → 3 readings + format_battery E2E -----

    /// Story 3.3 Happy Path #1. Cited: Story 3.3 TDD contract.
    /// Fixture: in-process mock. Threshold T-1 (Lightweight).
    ///
    /// Mock battery 78% Charging → emits exactly three readings
    /// (BatteryPercent, BatteryState, BatteryPowerRate). Cross-checks the
    /// end-to-end pipeline by formatting the percent+state pair with
    /// `format_battery` (Story 1.3) — must produce `"78% (Charging)"`.
    #[test]
    fn mock_battery_78_charging_yields_three_readings_and_format_battery() {
        let snap = BatterySnapshot {
            index: 0,
            percent: 78.0,
            state: BatterySnapshotState::Charging,
            energy_rate_watts: -12.5, // negative = charging on AC (Boundary #3)
        };
        let readings = readings_from_snapshot(std::slice::from_ref(&snap));
        // Contract: exactly 3 readings for one battery (percent, state, rate).
        assert_eq!(
            readings.len(),
            3,
            "one battery should yield percent + state + rate (3 readings)"
        );

        // BatteryPercent: 78.0, Unit::Percent.
        let pct = readings
            .iter()
            .find(|r| r.kind == MetricKind::BatteryPercent)
            .expect("BatteryPercent reading present");
        assert!((pct.value - 78.0).abs() < f64::EPSILON);
        assert_eq!(pct.unit, Unit::Percent);

        // BatteryState: Charging (ordinal 0.0).
        let st = readings
            .iter()
            .find(|r| r.kind == MetricKind::BatteryState)
            .expect("BatteryState reading present");
        let domain_state = BatteryState::from_value(st.value);
        assert_eq!(
            domain_state,
            BatteryState::Charging,
            "BatteryState value must round-trip to Charging"
        );

        // BatteryPowerRate: -12.5 W (negative = charging per Boundary #3).
        let rate = readings
            .iter()
            .find(|r| r.kind == MetricKind::BatteryPowerRate)
            .expect("BatteryPowerRate reading present");
        assert!((rate.value - (-12.5)).abs() < f64::EPSILON);
        assert_eq!(rate.unit, Unit::Watts);

        // End-to-end cross-check with Story 1.3's format_battery. The percent
        // is 78 (rounded to u8), state is Charging — must produce the canonical
        // PRD §7.1 string. Clamp before the cast: pct is in 0..=100 from a
        // finite filter, so the clamp is a no-op in practice but documents the
        // contract and silences clippy::cast_sign_loss.
        let pct_clamped = pct.value.round().clamp(0.0, 100.0);
        // pct_clamped is finite (T-20) and clamped to 0.0..=100.0, so the cast
        // is safe. Both lints are pedantic about the general f64→u8 truncation.
        #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
        let pct_u8 = pct_clamped as u8;
        let formatted = format_battery(pct_u8, domain_state);
        assert_eq!(formatted, "78% (Charging)");
    }

    // ----- Happy Path #1b: descriptor correctness (Tier::Basic + Lightweight) -----

    /// Cited: Story 3.3 Technical Context (Tier::Basic, Lightweight). Cross-
    /// checks the classifier contract (Story 2.3).
    #[test]
    fn descriptor_is_basic_tier_lightweight() {
        let adapter = BatteryAdapter::new();
        let d = adapter.descriptor();
        assert_eq!(d.name, "battery");
        assert_eq!(d.cost_class, CostClass::Lightweight);
        assert_eq!(d.requires_tier, ProviderTier::Basic);
        assert!(d.metrics.contains(&MetricKind::BatteryPercent));
        assert!(d.metrics.contains(&MetricKind::BatteryState));
        assert!(d.metrics.contains(&MetricKind::BatteryPowerRate));
    }

    // ----- Boundary #1: No battery → empty -----

    /// Story 3.3 Boundary #1. Cited: Story 3.3 TDD contract.
    /// Desktops without a battery MUST get an empty vec — never a panic.
    #[test]
    fn no_battery_emits_empty_vec() {
        let snaps: Vec<BatterySnapshot> = Vec::new();
        let readings = readings_from_snapshot(&snaps);
        assert!(
            readings.is_empty(),
            "no batteries → zero readings (must not panic)"
        );
    }

    // ----- Boundary #2: 100% idle → BatteryState::Idle -----

    /// Story 3.3 Boundary #2. Cited: Story 3.3 TDD contract.
    /// A 100%-full idle battery (AC connected, not actively charging) MUST
    /// report `BatteryState::Idle`. This mirrors the `State::Full → Idle`
    /// mapping in `backend::state_from_battery`.
    #[test]
    fn full_idle_battery_reports_idle_state() {
        let snap = BatterySnapshot {
            index: 0,
            percent: 100.0,
            state: BatterySnapshotState::Idle,
            energy_rate_watts: 0.0,
        };
        let readings = readings_from_snapshot(std::slice::from_ref(&snap));
        let st = readings
            .iter()
            .find(|r| r.kind == MetricKind::BatteryState)
            .expect("BatteryState reading present");
        assert_eq!(
            BatteryState::from_value(st.value),
            BatteryState::Idle,
            "100% idle battery must map to BatteryState::Idle"
        );
        // Percent is still emitted as 100.0.
        let pct = readings
            .iter()
            .find(|r| r.kind == MetricKind::BatteryPercent)
            .expect("BatteryPercent reading present");
        assert!((pct.value - 100.0).abs() < f64::EPSILON);
    }

    // ----- Boundary #3: rate sign convention (negative on AC = charging) -----

    /// Story 3.3 Boundary #3. Cited: Story 3.3 TDD contract.
    /// `energy_rate_watts` passes through verbatim — negative = charging on AC.
    /// The adapter MUST NOT normalize the sign; the GUI renders it as-is.
    #[test]
    fn power_rate_sign_passes_through_unchanged() {
        // Charging case: negative rate.
        let charging = BatterySnapshot {
            index: 0,
            percent: 50.0,
            state: BatterySnapshotState::Charging,
            energy_rate_watts: -10.0,
        };
        let r = readings_from_snapshot(std::slice::from_ref(&charging));
        let rate = r
            .iter()
            .find(|x| x.kind == MetricKind::BatteryPowerRate)
            .unwrap();
        assert!(
            rate.value < 0.0,
            "charging rate is negative; got {}",
            rate.value
        );

        // Discharging case: positive rate.
        let discharging = BatterySnapshot {
            index: 0,
            percent: 50.0,
            state: BatterySnapshotState::Discharging,
            energy_rate_watts: 7.5,
        };
        let r = readings_from_snapshot(std::slice::from_ref(&discharging));
        let rate = r
            .iter()
            .find(|x| x.kind == MetricKind::BatteryPowerRate)
            .unwrap();
        assert!(
            rate.value > 0.0,
            "discharging rate is positive; got {}",
            rate.value
        );
    }

    // ----- Boundary #4: T-20 NaN filter (NaN percent/rate is omitted) -----

    /// Cited: T-20 (finite only). If a driver returns NaN for percent or rate
    /// (some Windows ACPI drivers do this when idle), the NaN reading is
    /// OMITTED — not emitted with a sentinel. The state reading is always
    /// finite (it's an ordinal) and is always emitted.
    #[test]
    fn nan_percent_or_rate_is_omitted_per_t20() {
        let snap = BatterySnapshot {
            index: 0,
            percent: f64::NAN,
            state: BatterySnapshotState::Discharging,
            energy_rate_watts: f64::NAN,
        };
        let readings = readings_from_snapshot(std::slice::from_ref(&snap));
        // No NaN anywhere in the output.
        assert!(
            readings.iter().all(|r| r.value.is_finite()),
            "T-20: no reading value may be NaN/Inf"
        );
        // BatteryState is always finite (ordinal 0..=3); always emitted.
        assert!(
            readings.iter().any(|r| r.kind == MetricKind::BatteryState),
            "BatteryState is always finite and always emitted"
        );
        // Percent + rate were NaN → dropped.
        assert!(readings
            .iter()
            .all(|r| r.kind != MetricKind::BatteryPercent));
        assert!(readings
            .iter()
            .all(|r| r.kind != MetricKind::BatteryPowerRate));
    }

    // ----- Boundary #5: two batteries → 6 readings -----

    /// Cited: Story 3.3 Boundary #1 implies multi-battery enumeration works.
    /// Some laptops have two batteries (e.g. ThinkPad with internal + hot-
    /// swappable). Each produces 3 readings with distinct SensorId instances.
    #[test]
    fn two_batteries_yield_six_readings_with_distinct_instances() {
        let snaps = vec![
            BatterySnapshot {
                index: 0,
                percent: 80.0,
                state: BatterySnapshotState::Charging,
                energy_rate_watts: -5.0,
            },
            BatterySnapshot {
                index: 1,
                percent: 60.0,
                state: BatterySnapshotState::Discharging,
                energy_rate_watts: 3.0,
            },
        ];
        let readings = readings_from_snapshot(&snaps);
        assert_eq!(readings.len(), 6, "2 batteries × 3 readings each");
        // Instance strings are distinct per battery index.
        let instances: std::collections::HashSet<&str> = readings
            .iter()
            .map(|r| r.sensor.instance.as_str())
            .collect();
        assert!(instances.contains("0"));
        assert!(instances.contains("1"));
    }

    // ----- G15: Mutex poisoning recovery -----

    /// The adapter MUST NOT propagate Mutex *poison* errors to the poller.
    /// Cited: guardrails.md G15. If a previous `read_all` panicked mid-lock,
    /// the next call MUST recover via `PoisonError::into_inner` rather than
    /// propagating the poison.
    #[test]
    fn read_all_recovers_from_mutex_poison() {
        use std::sync::atomic::{AtomicBool, Ordering};
        use std::sync::Arc as StdArc;
        let panicked = StdArc::new(AtomicBool::new(false));
        let backend = OncePanicBackend {
            panicked: panicked.clone(),
        };
        let adapter = StdArc::new(BatteryAdapterGeneric::with_backend(backend));
        // First call: panics inside the lock, poisoning the Mutex.
        let a1 = adapter.clone();
        let h = std::thread::spawn(move || a1.read_all());
        let _ = h.join(); // thread panicked — that's expected.
        assert!(panicked.load(Ordering::SeqCst), "first call must have run");
        // Second call: the Mutex is poisoned, but `read_all` recovers via
        // `unwrap_or_else(|e| e.into_inner())`. The backend's panic-flag is
        // already set, so it returns an empty snapshot this time.
        let v = adapter.read_all();
        assert!(
            v.iter().all(|r| r.value.is_finite()),
            "poison recovery yields finite readings"
        );
    }

    /// Backend that panics on the first `refresh_and_snapshot` call, then
    /// returns an empty snapshot on subsequent calls. Used to poison the
    /// adapter Mutex and verify recovery.
    struct OncePanicBackend {
        panicked: Arc<std::sync::atomic::AtomicBool>,
    }
    impl BatteryBackend for OncePanicBackend {
        fn refresh_and_snapshot(&mut self) -> Vec<BatterySnapshot> {
            if !self
                .panicked
                .swap(true, std::sync::atomic::Ordering::SeqCst)
            {
                panic!("poison on first call");
            }
            Vec::new()
        }
    }

    // ----- Real backend smoke (machine with battery) -----

    /// Smoke test that the production `RealBatteryBackend` constructs and
    /// returns SOME readings on the dev machine (which has a battery at 96%
    /// charging). Not a contract test — just a "did the wiring compile + run"
    /// guard. On a battery-less machine this test still passes (empty vec is
    /// the correct no-battery behavior per Boundary #1).
    #[test]
    fn real_backend_returns_some_readings() {
        let adapter = BatteryAdapter::new();
        let readings = adapter.read_all();
        // On this dev machine (battery present), expect 3 readings per
        // battery. On a desktop we'd accept 0 — so we only assert that all
        // emitted readings are finite (T-20) and well-typed.
        assert!(
            readings.iter().all(|r| r.value.is_finite()),
            "real backend readings must all be finite (T-20)"
        );
        // Any percent reading must be in 0..=100.
        for r in &readings {
            if r.kind == MetricKind::BatteryPercent {
                assert!(
                    (0.0..=100.0).contains(&r.value),
                    "battery percent out of range: {}",
                    r.value
                );
            }
        }
    }
}
